# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3801052d45896a0bc7bedb0c330a0747a6fdcc8feef011d423b0805ec648915f63c20360ec8a64c11ea2c25c6d94997c1644eeb8354e74c897a0035a5f8e2ef7

test:
  secret_key_base: 293a5ca8bf3c86baf31b7423b07ea0a8ce230db9b5c61b816cf9233df1ce305d333ef52dd7edefd76d43644ba5bbc86fc518827057d784bdfa08d21809d1c638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
